apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: training
  labels:
    app: testing
spec:
  selector:
    app: testing
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80
