apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deploy
  namespace: training
  labels:
    app: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
        ports:
        - containerPort: 80
      containers:
      - name: testing1
        image: bitbull/webserver
        ports:
        - containerPort: 80
