apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  namespace: training
  labels:
    name: testing
spec:
  containers:
  - name: testing
    image: bitbull/webserver
    ports:
    - containerPort: 80
