apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  namespace: training
  labels:
    app: testing
spec:
  containers:
  - name: testing
    image: bitbull/webserver
    ports:
    - containerPort: 80
