apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: training

spec:
  selector:
    app: testing
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort:
