apiVersion: v1
kind: Pod
metadata:
  name: pod-taint
  namespace: training
  labels:
    name: testing
spec:
  containers:
  - name: testing
    image: jenkins:2.60.3
  tolerations:              # effect can be NoSchedule or NoExectute 
  - key: "username"
    operator: "Equal"
    value: "password"
    effect: "NoSchedule"
