apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeaffinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: sum 
            operator: In
            values: 
            - add
            - longadd
           
  containers:
  - name: nodeaffinity
    image: bitbull/webserver
