apiVersion: v1
kind: PersistentVolume
metadata:
  name: t-pv
  namespace: training
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/tmp/pvdata"
