# Yaml file to allow access to Kubernetes API for users...

apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-brigade
  namespace: brigade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-brigade
  namespace: brigade
rules:                   # Authorization rules for this role
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-brigade
  namespace: brigade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-brigade
  namespace: brigade
subjects:
  - kind: ServiceAccount
    name: serviceaccount-brigade
  - kind: Group
    name: system:authenticated             # for all authenticated users
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: system:unauthenticated           # for all unauthenticated users
    apiGroup: rbac.authorization.k8s.io
