apiVersion: v1
kind: Secret
metadata:
  name: myownsecret
  namespace: training
data:
  username: c2h1YmhhbQ==
  password: c2VjcmV0cGFzc3dvcmQK

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-deploy
  namespace: training
  labels:
    app: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
        ports:
        - containerPort: 80
        env:
        - name: Mypassword
          valueFrom:
            secretKeyRef:
              name: myownsecret
              key: password
