apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: state
  namespace: training
  labels:
    app: state
spec:
  serviceName: ""      
  replicas: 2
  selector:
    matchLabels:
      app: state
  template:
    metadata:
      labels:
        app: state
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
